version: '3.8'

services:
  products-api:
    build: .
    ports:
      - 3005:3005
    depends_on:
      - mssqlserver
      - elasticsearch
    environment:
      - DB_CONNECTION_URI=Server=mssqlserver;Database=master;User Id=sa;Password=SqlP@ssW0rd;

  mssqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SqlP@ssW0rd"
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SqlP@ssW0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7.17.10
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch/data
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  elasticsearch_data:
